block-beta
    columns 3

    block:docs:1
        columns 1
        A["📄 Doc 1<br/>50K tokens"]
        B["📄 Doc 2<br/>30K tokens"]
        C["📄 Doc 3<br/>45K tokens"]
        D["📄 Doc 4<br/>20K tokens"]
    end

    arrow1<["❌ Won't fit!"]>(right)

    block:window:1
        columns 1
        W["Context Window<br/>8K tokens<br/>━━━━━━━━━━<br/><br/><br/><br/>"]
    end
